trees:
  tangtv:
    - \TANGTV::TOP.TANGTV:LODIV_240RM1:PAR:INTENSIFIED:VIDEO_IMAGES
    - \TANGTV::TOP.TANGTV:LODIV_240RM1:PAR:STANDARD:VIDEO_IMAGES
    - \TANGTV::TOP.TANGTV:LODIV_240RM1:PERP:STANDARD:VIDEO_IMAGES
    - \TANGTV::TOP.TANGTV:UPDIV_225RP1:PERP:STANDARD:VIDEO_IMAGES
    - \TANGTV::TOP.TANGTV:UPDIV_0RP1:PERP:STANDARD:VIDEO_IMAGES
    - \TANGTV::TOP.TANGTV:UPDIV_225RP1:PAR:STANDARD:VIDEO_IMAGES
    - \TANGTV::TOP.TANGTV:UPDIV_0RP1:PAR:STANDARD:VIDEO_IMAGES
  irtv:
    - \IRTV::TOP.IRTV:BIAS_105RM1:DIGITAL_CAM:DIGITAL_RAW
    - \IRTV::TOP.IRTV:LOCEN_315RM1:DIGITAL_CAM:DIGITAL_RAW
    - \IRTV::TOP.IRTV:LODIV_165RP2:DIGITAL_CAM:DIGITAL_RAW
    - \IRTV::TOP.IRTV:LODIV_60RP2:DIGITAL_CAM:DIGITAL_RAW
    - \IRTV::TOP.IRTV:PERI75R0:DIGITAL_CAM:DIGITAL_RAW
    - \IRTV::TOP.IRTV:UPCEN_300RP1:DIGITAL_CAM:DIGITAL_RAW
    - \IRTV::TOP.IRTV:UPDIV_225RM2:DIGITAL_CAM:DIGITAL_RAW

server: chiron.gat.com
